### ISSUE TITLE
/dev/kmsg Issue

### ISSUE THREAD

**Issue by aldycool** [digitalis-io/k3s-on-prem-production#5]
Hi @89luca89 ,

I'm still trying to adapt this to run in Ubuntu 20.04, now on the `k3s-deploy` role, I'm getting this error:

```
"Failed to run kubelet" err="failed to run Kubelet: failed to create kubelet: open /dev/kmsg: permission denied"
```

I've searched this error, and everything points to either non-root user, or LXD, but I know none of these is actually used in the configuration.

Do you know something that may have caused this? Thanks.

**Comment by 89luca89** [comment]
Hi @aldycool 
from a first search online it seems a problem between k8s and LXD, here is a discussion:

https://discuss.linuxcontainers.org/t/not-able-to-run-kubernetes-inside-docker-inside-lxd/4643

**Comment by aldycool** [comment]
Hi @89luca89 ,

Yes you're right, it is about the Ubuntu's LXD which is carried by `snap` in a fresh Ubuntu 20.04 installation, and it is installed by default (listed in the `snap list` command). I'll try remove it, but most likely this is what causing the error. Thanks again for your help!

**Comment by 89luca89** [comment]
No problem, cheers! :smile:
